### ISSUE TITLE
es4x/graalvm Integration Roadmap

### ISSUE THREAD

**Issue by frank-dspeed** [frank-dspeed/chromitex#1]
# Everything needed to run chromitex in a es4x like project

## why?
es4x is a eventloop abstraction for Java it is used in many web applications and the process model perfect fits the one from nodejs
while it is a JS.Context factory for GraalVM

## ToDo

- [ ] Create a minimal Example with hardcoded Java Spawn Process Pipe and puppeteer (Takes 1 Day)
- [ ] Create es4x-node pollyfills so that the buildin modules are replaced by Java/ES4X (Takes Weeks but fast progress but a lot of work)
- [ ] Create Packaging something like electron forge or make it work with that
- [ ] Create fiddle something like electron fiddle
